### ISSUE TITLE
Unbound value Unix.map_file

### ISSUE THREAD

**Issue by Earnestly** [ytomino/headmaster#4]
After manually correcting https://github.com/ytomino/headmaster/issues/3 by simply removing the `-h` flags I've run into this next issue:

Some system details:
* x86_64-pc-linux-gnu
* gcc (GCC) 7.2.0
* ocamlbuild 0.11.0
* ocaml 4.05.0

```
ocamlbuild -build-dir x86_64-pc-linux-gnu.build -X x86_64-pc-linux-gnu.build -X bin -I source -I source/ada -cflags "-g -safe-string -w Aer-48" main.native
Finished, 1 target (0 cached) in 00:00:01.
+ /usr/bin/ocamlc.opt -c -g -safe-string -w Aer-48 -I source -I source/ada -o source/textFile.cmo source/textFile.ml
File "source/textFile.ml", line 80, characters 4-17:
Error: Unbound value Unix.map_file
Command exited with code 2.
Compilation unsuccessful after building 60 targets (0 cached) in 00:00:04.
make: *** [Makefile;45: x86_64-pc-linux-gnu.build/headmaster] Error 10
```

I'm fairly unfamiliar with ocaml so I'm not entirely sure what this means.

**Comment by ytomino** [comment]
`Unix.map_file` is added from OCaml 4.06, to replace `Bigarray.map_file`.
Unfortunately `Bigarray.map_file` is deprecated now, so I rewrite it recently.
Update your OCaml, or revert 69b61285 at local.

**Comment by Earnestly** [comment]
Ah, I was trying to find change logs for OCaml but must have been looking at the wrong version.  No worries, I will soon be on 4.06 so this issue should be cleaned up then.

I'll close the issue now as you've answered everything and only reopen if I'm still having problems.

Thanks again
