### ISSUE TITLE
Unbound value find_opt

### ISSUE THREAD

**Issue by jklmnn** [ytomino/headmaster#6]
When I try to build headmaster I get the following error on Debian 9:
```
ocamlbuild -build-dir x86_64-linux-gnu.build -X x86_64-linux-gnu.build -X bin -I source -I source/ada -cflags "-g -safe-string -w Aer-48" main.native
Finished, 0 targets (0 cached) in 00:00:00.
+ /usr/bin/ocamlc.opt -c -g -safe-string -w Aer-48 -I source -I source/ada -o source/c_semantics.cmo source/c_semantics.ml
File "source/c_semantics.ml", line 9, characters 8-16:
Error: Unbound value find_opt
Command exited with code 2.
Compilation unsuccessful after building 19 targets (18 cached) in 00:00:00.
```

**Comment by ytomino** [comment]
Hello.

https://packages.debian.org/stretch/ocaml
The version of ocaml in Debian 9(stretch) seems 4.02. It's too old.
`Map.S.find_opt` is added from 4.05.

**Comment by jklmnn** [comment]
Thank you, that fixed that problem. Yet how does your makefile recognize paths of binaries? I had to uninstall the system package of ocaml even though the newer version was prepended in the path (and `which ocamlbuild` correctly showed the new version)? This is quite inconvenient since I had to remove all packages from my system that depend on ocaml. Also additionally to `rst2man.py` `rst2man` should be checked if the first one isn't available.

**Comment by ytomino** [comment]
Probably you don't need to uninstall the system OCaml.
How about trying `PATH=your/local/ocaml/bin:$PATH make`?

Certainly, `rst2man.py` is installed without the extension in Debian (and Ubuntu).
What shall I do...
For the time being, the makeshift 63587fb.

**Comment by jklmnn** [comment]
While the path was set correctly in my shell it seems that I didn't source the environemnt correctly. After completely leaving my shell and starting a new one the issue was gone. So I consider this fixed from my side.
